"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.singleton = exports.injectable = exports.inject = exports.MetadataScope = exports.getContainer = void 0;
var container_1 = require("./container");
Object.defineProperty(exports, "getContainer", { enumerable: true, get: function () { return container_1.getContainer; } });
var common_1 = require("./common");
Object.defineProperty(exports, "MetadataScope", { enumerable: true, get: function () { return common_1.MetadataScope; } });
var decorators_1 = require("./decorators");
Object.defineProperty(exports, "inject", { enumerable: true, get: function () { return decorators_1.inject; } });
Object.defineProperty(exports, "injectable", { enumerable: true, get: function () { return decorators_1.injectable; } });
Object.defineProperty(exports, "singleton", { enumerable: true, get: function () { return decorators_1.singleton; } });
